"""init_all_tables

Revision ID: b2a52180e78f
Revises: 
Create Date: 2026-03-03 16:51:55.336406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a52180e78f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability_tags', sa.JSON(), nullable=True),
    sa.Column('dify_endpoint', sa.String(length=500), nullable=False),
    sa.Column('dify_api_key', sa.String(length=500), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_params', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('confirm_before_exec', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('resource_name', sa.String(length=200), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasources',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('dify_endpoint', sa.String(length=500), nullable=True),
    sa.Column('dify_api_key', sa.String(length=500), nullable=True),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_params', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(length=20), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('sync_data_cache', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type')
    )
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasources_user_id'), ['user_id'], unique=False)

    op.create_table('execution_history',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('wagent_id', sa.String(length=36), nullable=True),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('output_result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('retry_attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_history_user_id'), ['user_id'], unique=False)

    op.create_table('llm_configs',
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('api_endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.BigInteger(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_alert_threshold', sa.Float(), nullable=True),
    sa.Column('user_preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purpose')
    )
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_configs_user_id'), ['user_id'], unique=False)

    op.create_table('llm_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('model_name', sa.String(length=200), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('related_type', sa.String(length=30), nullable=True),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('external_pushed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('notification_channels',
    sa.Column('channel_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('dify_endpoint', sa.String(length=500), nullable=False),
    sa.Column('dify_api_key', sa.String(length=500), nullable=False),
    sa.Column('input_mapping', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_type')
    )
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_channels_user_id'), ['user_id'], unique=False)

    op.create_table('notification_global_prefs',
    sa.Column('dnd_start', sa.String(length=5), nullable=True),
    sa.Column('dnd_end', sa.String(length=5), nullable=True),
    sa.Column('merge_strategy', sa.String(length=20), nullable=False),
    sa.Column('merge_window_minutes', sa.Integer(), nullable=False),
    sa.Column('deadline_advance_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_global_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_global_prefs_user_id'), ['user_id'], unique=False)

    op.create_table('notification_prefs',
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('wechat_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_type', name='uq_notification_prefs_user_message_type')
    )
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_prefs_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_plans',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_cron', sa.String(length=100), nullable=True),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_plans_user_id'), ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('task_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('picked_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todos',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=500), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('project', sa.String(length=200), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('orchestration_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_user_id'), ['user_id'], unique=False)

    op.create_table('wagents',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability_tags', sa.JSON(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_params', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('auto_execute', sa.Boolean(), nullable=False),
    sa.Column('confirm_before_exec', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wagents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagents_user_id'), ['user_id'], unique=False)

    op.create_table('workflows',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capability_tags', sa.JSON(), nullable=True),
    sa.Column('dify_endpoint', sa.String(length=500), nullable=False),
    sa.Column('dify_api_key', sa.String(length=500), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_params', sa.JSON(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_tasks',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('orchestration_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('wagent_id', sa.String(length=36), nullable=True),
    sa.Column('wagent_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('output_result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.Column('confirm_deadline', sa.DateTime(), nullable=True),
    sa.Column('confirm_action', sa.String(length=20), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['schedule_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('wagent_versions',
    sa.Column('wagent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('input_params', sa.JSON(), nullable=False),
    sa.Column('output_params', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['wagent_id'], ['wagents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wagent_id', 'version', name='uq_wagent_version')
    )
    with op.batch_alter_table('wagent_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wagent_versions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wagent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagent_versions_user_id'))

    op.drop_table('wagent_versions')
    with op.batch_alter_table('schedule_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_tasks_user_id'))

    op.drop_table('schedule_tasks')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_user_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('wagents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wagents_user_id'))

    op.drop_table('wagents')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_user_id'))

    op.drop_table('todos')
    op.drop_table('task_queue')
    op.drop_table('system_settings')
    with op.batch_alter_table('schedule_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_plans_user_id'))

    op.drop_table('schedule_plans')
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_prefs_user_id'))

    op.drop_table('notification_prefs')
    with op.batch_alter_table('notification_global_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_global_prefs_user_id'))

    op.drop_table('notification_global_prefs')
    with op.batch_alter_table('notification_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_channels_user_id'))

    op.drop_table('notification_channels')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))

    op.drop_table('messages')
    op.drop_table('llm_usage_logs')
    with op.batch_alter_table('llm_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_configs_user_id'))

    op.drop_table('llm_configs')
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_history_user_id'))

    op.drop_table('execution_history')
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasources_user_id'))

    op.drop_table('datasources')
    op.drop_table('audit_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_user_id'))

    op.drop_table('agents')
    # ### end Alembic commands ###
